### ISSUE TITLE
starting error 

### ISSUE THREAD

**Issue by pretech86** [arjunindia/fb-phisher-python#1]
when i try python3 app.py it give me the following error

 File "app.py", line 13
    return render_template('b.html')
                                   ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by arjunindia** [comment]
Sorry, i just realised it is python 2, updating everything in readme.md.
Thanks!
IDK why i did that.

**Comment by arjunindia** [comment]
It should work by now. THANKS!

**Comment by arjunindia** [comment]
In case it still persists, comment here.

**Comment by pretech86** [comment]
It working now thanks , can you add redirection link to the tool like any phishing tool

**Comment by arjunindia** [comment]
Actually what you have to do to redirect is to edit b.html inside templates

**Comment by arjunindia** [comment]
New update!
The tool is going to have an install.sh file, install it using terminal and now run the tool using command facebooker. if you run like that, it will give you the option to change the redirect link!
